name: CI

on:
  push:
    branches: [ main, '*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install --with-deps
    - name: Run unit + integration tests
      run: |
        pytest -q
    - name: Start server for e2e and run e2e tests
      run: |
        nohup uvicorn main:app --host 127.0.0.1 --port 8000 &
        # give server time to start
        sleep 2
        pytest -q tests/e2e -k playwright_e2e || (sleep 1 && pytest -q tests/e2e -k playwright_e2e)
